### PR TITLE
upgraded libs to newest versions

### LINKED ISSUE #8: Upgrading libs and differentiate to Microsoft.Data.SqlClient vs System.Data.SqlClient
Microsoft released Microsoft.Data.SqlClient and it would be nice if library will cover that case

### PR DESCRIPTION
**Pull request by AdaskoTheBeAsT**
fixes #8

### CODE REVIEW

**Comment by simonfox** [comment]
@mattjohnsonpint any reason this PR hasn't been looked at?

**Comment by mattjohnsonpint** [comment]
Mainly because I just haven't had the time to focus on this.  Sorry.  I'll try to get to it soon.

**Comment by simonfox** [comment]
No need to be sorry. Thank you for your efforts with this package!

**Comment by 0xced** [comment]
Please have a look at #12 instead which does not take a dependency on neither System.Data.SqlClient nor Microsoft.Data.SqlClient.

**Comment by AdaskoTheBeAsT** [comment]
Rusted ;) closing

**Pull request closed without merging**
